export {default as img1} from "../media/images/img-1.jpg";
export {default as img2} from "../media/images/img-2.jpg";
export {default as img3} from "../media/images/img-3.jpg";
export {default as img4} from "../media/images/img-4.jpg";
export {default as img5} from "../media/images/img-5.jpg";
export {default as img6} from "../media/images/img-6.jpg";
export {default as img7} from "../media/images/img-7.jpg";
export {default as img8} from "../media/images/img-8.jpg";
export {default as img9} from "../media/images/img-9.jpg";